### ISSUE TITLE
Read count doesn't update

### ISSUE THREAD

**Issue by s-boardman** [robertaboukhalil/fastq.bio#2]
Uploading a fastq displays the data, but the sampled read count on the plots does not update (see attached).
![newplot](https://user-images.githubusercontent.com/3591844/30314775-b8e8991e-9799-11e7-80d2-dd6d9a802b1e.png)

Love the app overall though! :100:

**Comment by robertaboukhalil** [comment]
Glad you like it!

I have a few questions to help diagnose this issue:
- Can you send me the FASTQ file you used (or just the top 2K reads)?
- Do you see the same "0K" issue when you click on "Use Sample FASTQ"?

**Comment by s-boardman** [comment]
Hi @robertaboukhalil I don't have the same issue with the sample fastq (good question!).

It also works with the [Platinum Genomes](https://www.ebi.ac.uk/ena/data/view/PRJEB3381) fastqs though

I am not be able to send you a fastq as I'm working on clincal data. But if I zcat the first 4000 reads and dump them in a new fastq, then gzip it works. I shall try to dig out a research run and see whether we get the same issue.

PS I'm using Chrome Version 61.0.3163.79 (Official Build) (64-bit)

**Comment by robertaboukhalil** [comment]
That's strange, can you check the console log as well? It should tell you how many reads are being read.

**Comment by s-boardman** [comment]
This is the console log I get. The first set of output is for my "normal" fastq file (up to the first line marked :five: ). The second set is the "test" fastq file, which is just the first 3000 reads from the "normal" one. Very strange.

![fastq_bio_console](https://user-images.githubusercontent.com/3591844/30365260-19b48e0e-985f-11e7-922d-0eacc91548e9.PNG)

**Comment by robertaboukhalil** [comment]
That is strange indeed. Just to make sure, the first set of output is your gzipped FASTQ, and the second set of output where you did zcat -> gzip on it?

If so, it may be that the first file was gzipped in a different way that isn't supported here?

Can you try running the `file` command on your original file: `file original_fastq.gz` and see if it says something other than `gzip compression`?

**Comment by s-boardman** [comment]
Ah there is a difference between the pipeline derived fastq.gz and the subsequent downsampled version I created. I wonder what it is!?

```
$ file pipeline_output.fastq.gz
pipeline_output.fastq.gz: gzip compressed data, extra field

$file test.fastq.gz 
test.fastq.gz: gzip compressed data, was "test.fastq", last modified: Tue Sep 12 14:48:24 2017, from Unix
```

**Comment by robertaboukhalil** [comment]
Interesting, I don't usually see the "extra field" part when running `file`. It's possible the library I'm using for gzip parsing doesn't support those extra fields.
